# Generated by Django 5.2.11 on 2026-02-23 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="survivorcluster",
            old_name="confidece_score",
            new_name="confidence_score",
        ),
    ]
