# Generated by Django 5.2.11 on 2026-03-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_confidece_score_survivorcluster_confidence_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="damagereport",
            name="damage_type",
            field=models.CharField(
                choices=[
                    ("WATER", "Water (Natural or Flood)"),
                    ("BUILDING_NO_DAMAGE", "Building - No Damage"),
                    ("BUILDING_MINOR_DAMAGE", "Building - Minor Damage"),
                    ("BUILDING_MAJOR_DAMAGE", "Building - Major Damage"),
                    ("BUILDING_TOTAL_DESTRUCTION", "Building - Total Destruction"),
                    ("VEHICLE", "Vehicle"),
                    ("ROAD_CLEAR", "Road - Clear"),
                    ("ROAD_BLOCKED", "Road - Blocked"),
                    ("TREE", "Tree"),
                    ("POOL", "Pool"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
